MAF/maf/config/routes.rb
Rails.application.routes.draw do

  resources :line_items

  resources :carts

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'welcome/index'

  resources :wines do
    get 'search', on: :collection
    get 'price_filter', on: :collection
  end

  resources :customers

   root 'welcome#index'

end

MAF/maf/app/models/wine.rb
class Wine < ActiveRecord::Base
  has_many :line_items

  before_destroy :ensure_not_referenced_by_any_line_item

  # Set wine name
  def name=(value)
    write_attribute :name, (value ? value.humanize : nil)
  end

  # Method does a SQL-style 'select where' to get anything in Wines table
  # that has anything from the 'query' parameter
  def self.like(query)
    if query.nil?
      []
    else
      if Rails.env.development?
          where('name LIKE :query ' +
            'OR short_description LIKE :query ' +
            'OR supplier LIKE :query ' +
            'OR price LIKE :query ' +
            'OR bottle_size_in_ml LIKE :query ' +
            'OR country_of_origin LIKE :query ' +
            'OR grade_type LIKE :query ' +
            'OR long_description LIKE :query',
            query: "%#{query}%")
      elsif Rails.env.production?
        where('name LIKE :query ' +
            'OR short_description LIKE :query ' +
            'OR supplier LIKE :query ' +
            'OR text(price) LIKE :query ' +
            'OR text(bottle_size_in_ml) LIKE :query ' +
            'OR country_of_origin LIKE :query ' +
            'OR grade_type LIKE :query ' +
            'OR long_description LIKE :query',
            query: "%#{query}%")
      end
    end
  end

  def self.price_like(lowest_price_query, highest_price_query)
    if lowest_price_query.nil? && highest_price_query.nil?
      []
    else
      where("price >= :lowest_price_query AND price <= :highest_price_query",
        {lowest_price_query: lowest_price_query, 
        highest_price_query: highest_price_query})
    end
  end

  # Setting number of wines on a page - used by pagination gem
  self.per_page = 4

  private
  # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end
end

MAF/maf/app/controllers/wines_controller.rb
require 'rexml/document'
require 'open-uri'

class WinesController < ApplicationController
  include ApplicationHelper
  before_action :set_current_page, except: [:index]
  before_action :set_wine, only: [:show, :edit, :update, :destroy]
  helper_method :get_wine_image_url, :get_supplier_data_state


  # GET /wines
  # GET /wines.json
  def index
    @cart = current_cart
    get_all_wines(false)
    @wines = Wine.paginate(:page => params[:page],:per_page => params[:per_page]).order('name')
  end

  # GET /wines/1
  # GET /wines/1.json
  def show
    @cart = current_cart
  end

  # GET /wines/new
  def new
    @cart = current_cart
    @wine = Wine.new
  end

  # GET /wines/1/edit
  def edit
    @cart = current_cart
  end

  # Search method is called to search from cached wine data in the database
  def search
    @cart = current_cart
    @wines = Wine.like(params[:query]).paginate(page: params[:page], per_page: params[:per_page]).order('name')
    if request.xhr?
      render partial: 'wines_list', object: @wines, layout: false
    else
      render 'index'
    end
  end

  def price_filter
    @cart = current_cart
    if params[:lowest_price_query].nil? || params[:lowest_price_query] == 0
      params[:lowest_price_query] = 0
    end
    if params[:highest_price_query].nil? || params[:highest_price_query] < params[:lowest_price_query] || params[:highest_price_query] == 0
      params[:highest_price_query] = 999
    end

    if params[:lowest_price_query] == "" && params[:highest_price_query] == ""
      params[:lowest_price_query] = 0
      params[:highest_price_query] = 999
    end

    @wines = Wine.price_like(params[:lowest_price_query], params[:highest_price_query]).paginate(page: params[:page], per_page: params[:wine_per_page]).order('name')
    if request.xhr?
      render partial: 'wines_list', object: @wines, layout: false
    else
      render 'index'
    end
  end

  def get
  end

  # POST /wines
  # POST /wines.json
  def create
    respond_to do |format|
      if @wine.save
        format.html { redirect_to @wine, notice: 'Wine was successfully created.' }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /wines/1
  # PATCH/PUT /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: 'Wine was successfully updated.' }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1
  # DELETE /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url(page: @current_page), notice: 'Wine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_wine
    @wine = Wine.find(params[:id])
  end

  def set_current_page
    @current_page= params[:page] || 1
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def wine_params
    params.require(:wine).permit(:id, :lowest_price_query, :query, :highest_price_query, :wine_per_page , :wine_unique_number , :name, :image_url, :short_description,
                                 :bottle_size_in_ml, :price, :long_description, :country_of_origin, :grade_type, :suitable_for_vegetarians, :supplier, :image_file_name, :last_modified)
  end
end

MAF/maf/app/helpers/wines_helper.rb
module WinesHelper
	include ApplicationHelper

end

MAF/maf/app/views/wines/_form.html.erb
<%= form_for(@wine) do |f| %>
  <% if @wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% @wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MAF/maf/app/views/wines/_wines_list.erb
<br>
<div class="row">
<% @wines.each do |wine| %>
  <div class="col-md-3">
    <div class="thumbnail" style="background-color:rgb(241, 248, 249);">
      <%= link_to(image_tag(get_wine_image_url(wine), alt: 'Wine', title: 'Show details', :class => "wineThumbImage"), wine_path(wine)) %>
      <div class="caption">
        <h3><%= wine.name%></h3>
        <p><%= wine.short_description%><br>
        <strong>Bottle size(ml): </strong> <%= wine.bottle_size_in_ml%><br><br>
        <strong>£<%= !wine.price.nil? ? "%.2f" % wine.price : 0 %> per bottle</strong><br>
        <em>Wine Supplied by <%= wine.supplier%></em>
        </p>
        <%= form_tag(line_items_path(wine_id: wine)) do %>
          <p>Quantity: <%= number_field_tag "the_quantity", nil, :class => "quantityTextBox", placeholder: "1", min: "1", max: "99999" %>
          <%= submit_tag "Add to basket", :class => "btn btn-primary", :id => "addToBasket",data: {disable_with: "Add to basket"} %> </p>
        <% end %>
      </div>
    </div>
  </div>	
<% end %>
</div>
<br/>
<div class="digg_pagination">
  <div>
    <%= page_entries_info @wines %>
  </div>
  <%= will_paginate @wines, container: false %>
</div>
<br/>

MAF/maf/app/views/wines/edit.html.erb
<h1>Editing wine</h1>

<%= render 'form' %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path(page: @current_page) %>

MAF/maf/app/views/wines/index.html.erb
<h2 class="page-title">Non-Alcoholic Wines</h2>
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>

<% if @wines.length > 0 %>
	<!-- Search Field -->
	<div class="container">
		<div class="row searchfield">
			<div class="col-md-5">
			  <%= form_tag(search_wines_path, method: "get", id: "search") do %>
			    <fieldset>
			      <%= text_field_tag(:query,'',autocomplete: 'off', placeholder: "Search for Wine", :class => "form-control") %>
			    </fieldset>
			  <% end %>
		  	</div>
		  	<div class="col-md-7"> 
				<%= form_tag(price_filter_wines_path, method: "get", id: "price_filter", :class => "form-inline") do %>
					<div class="form-group"> or Filter by Price - 
						<label for="lowest_price_query">Lowest:</label>	  		
			  			<%= text_field_tag(:lowest_price_query,'',autocomplete: 'off', placeholder: "0", :class => "form-control", :style => "width: 60px") %> 
		  			</div>
		  			<div class="form-group">
			  			<label for="highest_price_query">Highest:</label>	
				  		<%= text_field_tag(:highest_price_query,'',autocomplete: 'off', placeholder: "999", :class => "form-control", :style => "width: 60px") %>
		  			</div>
		  			<div class="form-group">| Wines per page
			  			<select class="form-control" id="wine_per_page">
						  <option selected="selected">4</option>
						  <option>8</option>
						  <option>12</option>
						  <option>16</option>
						  <option>20</option>
						</select>
					</div>
		  		<% end %>

			</div>
		</div>
	</div>

	<div id='main-input-area'>
		<div class="container">
		  <%= render partial: 'wines_list', object: @wines %>
		</div>
	</div>
<% end %>

MAF/maf/app/views/wines/new.html.erb
<h1>New wine</h1>

<%= render 'form' %>

<%= link_to 'Back', wines_path(page: @current_page) %>

MAF/maf/app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>
<br><br>
<div class="container">
	<div class="row">				
		<div class="col-md-5">		
			<div class="thumbnail" style="background-color:rgb(241, 248, 249);">
				<%= image_tag(get_wine_image_url(@wine), alt: 'Wine', :class => "wineBigImage") %>
			</div>
		</div>
		<div class="col-md-7">		
			<h3><%= @wine.name %></h3>	
			<p><strong>Description: </strong><%= @wine.long_description %></p><br>
			<p><strong>Country of Origin: </strong><%= @wine.country_of_origin %></p>
			<p><strong>Grade Type: </strong><%= @wine.grade_type %></p>
			<p><strong>Suitable For Vegetarians?: </strong><%= @wine.suitable_for_vegetarians ? "Yes" : "No" %></p>
			<p><strong>Bottle Size: </strong><%= @wine.bottle_size_in_ml %>ml</p>

			<h2>£<%= !@wine.price.nil? ? "%.2f" % @wine.price : 0 %> per bottle</h2>
			<em>Wine is supplied by <%= @wine.supplier%></em>
			<br><br>
			<%= form_tag(line_items_path(wine_id: @wine)) do %>
	          <p>Quantity: <%= number_field_tag "the_quantity", nil, :class => "quantityTextBox", placeholder: "1", min: "1", max: "99999" %>
	          <%= submit_tag "Add to basket", :class => "btn btn-primary", :id => "addToBasket", data: {disable_with: "Add to basket"} %> </p>
	        <% end %>
		</div>
	</div>
</div>

<%= link_to 'Back', wines_path(page: @current_page), data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Returning to wines list...."} %>