SuppliersWebServices/WelshWineShop/config/routes.rb
Rails.application.routes.draw do
  resources :orders

  resources :wines

   root 'wines#index'

end

SuppliersWebServices/WelshWineShop/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :wine
end

SuppliersWebServices/WelshWineShop/app/models/wine.rb
class Wine < ActiveRecord::Base
	validates :name, :short_description, :bottle_size_in_ml, :price, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :name, uniqueness: true
	has_many :orders, dependent: :destroy
	
	has_attached_file :image
  	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  	#Get the most recently added wine
  	def self.latest
  		Wine.order('updated_at desc').limit(1).first
  	end
end

SuppliersWebServices/WelshWineShop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

SuppliersWebServices/WelshWineShop/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:customer_name, :customer_address, :customer_email, :quantity, :wine_id)
    end
end

SuppliersWebServices/WelshWineShop/app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: [:show, :edit, :update, :destroy]

  # GET /wines
  # GET /wines.json
  def index
    @wines = Wine.all
    @wines = set_wine_image @wines

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @wines }
      format.json { render json: @wines }
    end
  end

  # Method gets wines image absolute URL and stores it inside another array
  def set_wine_image(wines)
    @all_wine = Array.new
    wines.each do |wine|
      wine.image_url = wine.image.url
      @all_wine.push(wine)
    end
    @all_wine
  end

  # GET /wines/1
  # GET /wines/1.json
  def show
    respond_to do |format|
      if stale?(etag: @wine, last_modified: @wine.updated_at)
        format.html # show.html.erb
        format.xml  { render xml: @wine }
        format.json { render json: @wine }
      end
    end
  end

  # GET /wines/new
  def new
    @wine = Wine.new
  end

  # GET /wines/1/edit
  def edit
  end

  # POST /wines
  # POST /wines.json
  def create
    @wine = Wine.new(wine_params)

    # Set wine's image absolute URL as another column in the DB table 
    # - such column is exposed to web clients
    @wine.image_url = @wine.image.url

    respond_to do |format|
      if @wine.save
        format.html { redirect_to @wine, notice: 'Wine was successfully created.' }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1
  # PATCH/PUT /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: 'Wine was successfully updated.' }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1
  # DELETE /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: 'Wine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wine_params
      params.require(:wine).permit(:name, :data, :image_url, :short_description, :image, :bottle_size_in_ml, :price, :long_description, :country_of_origin, :grade_type, :suitable_for_vegetarians)
    end
end

SuppliersWebServices/WelshWineShop/app/helpers/application_helper.rb
module ApplicationHelper
end

SuppliersWebServices/WelshWineShop/app/helpers/orders_helper.rb
module OrdersHelper
end

SuppliersWebServices/WelshWineShop/app/helpers/wines_helper.rb
module WinesHelper
end

SuppliersWebServices/WelshWineShop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WelshWineShop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

SuppliersWebServices/WelshWineShop/app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_name %><br>
    <%= f.text_field :customer_name %>
  </div>
  <div class="field">
    <%= f.label :customer_address %><br>
    <%= f.text_field :customer_address %>
  </div>
  <div class="field">
    <%= f.label :customer_email %><br>
    <%= f.text_field :customer_email %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :wine_id %><br>
    <%= f.text_field :wine_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SuppliersWebServices/WelshWineShop/app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

SuppliersWebServices/WelshWineShop/app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table border="1">
  <thead>
    <tr>    
      <th>Wine ID</th>
      <th>Wine Name</th>
      <th>Quantity</th>
      <th>Customer name</th>
      <th>Customer address</th>
      <th>Customer email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>      
        <td><%= order.wine.id %></td>
        <td><%= order.wine.name %></td>
        <td><%= order.quantity %></td>
        <td><%= order.customer_name %></td>
        <td><%= order.customer_address %></td>
        <td><%= order.customer_email %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

SuppliersWebServices/WelshWineShop/app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

SuppliersWebServices/WelshWineShop/app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer name:</strong>
  <%= @order.customer_name %>
</p>

<p>
  <strong>Customer address:</strong>
  <%= @order.customer_address %>
</p>

<p>
  <strong>Customer email:</strong>
  <%= @order.customer_email %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order.quantity %>
</p>

<p>
  <strong>Wine:</strong>
  <%= @order.wine %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

SuppliersWebServices/WelshWineShop/app/views/wines/_form.html.erb
<%= form_for(@wine) do |f| %>
  <% if @wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% @wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :short_description %><br>
    <%= f.text_field :short_description %>
  </div>
  <div class="field">
    <%= f.label :bottle_size_in_ml %><br>
    <%= f.text_field :bottle_size_in_ml %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :long_description %><br>
    <%= f.text_field :long_description %>
  </div>
  <div class="field">
    <%= f.label :country_of_origin %><br>
    <%= f.text_field :country_of_origin %>
  </div>
  <div class="field">
    <%= f.label :grade_type %><br>
    <%= f.text_field :grade_type %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :suitable_for_vegetarians %><br>
    <%= f.check_box :suitable_for_vegetarians %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SuppliersWebServices/WelshWineShop/app/views/wines/edit.html.erb
<h1>Editing wine</h1>

<%= render 'form' %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

SuppliersWebServices/WelshWineShop/app/views/wines/index.html.erb
<h1>Listing wines</h1>

<table border="1">
  <thead>
    <tr>
      <th>Name</th>
      <th>Image url</th>
      <th>Short description</th>
      <th>Bottle size in ml</th>
      <th>Price</th>
      <th>Long description</th>
      <th>Country of origin</th>
      <th>Grade type</th>
      <th>Image</th>      
      <th>Suitable for vegetarians</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.name %></td>
        <td><%= wine.image_url %></td>
        <td><%= wine.short_description %></td>
        <td><%= wine.bottle_size_in_ml %></td>
        <td><%= wine.price %></td>
        <td><%= wine.long_description %></td>
        <td><%= wine.country_of_origin %></td>
        <td><%= wine.grade_type %></td>
        <td><%= wine.image %></td>        
        <td><%= wine.suitable_for_vegetarians %></td>
        <td><%= link_to 'Show', wine %></td>
        <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
        <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wine', new_wine_path %>

SuppliersWebServices/WelshWineShop/app/views/wines/new.html.erb
<h1>New wine</h1>

<%= render 'form' %>

<%= link_to 'Back', wines_path %>

SuppliersWebServices/WelshWineShop/app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine.name %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @wine.image_url %>
</p>

<p>
  <strong>Short description:</strong>
  <%= @wine.short_description %>
</p>

<p>
  <strong>Bottle size in ml:</strong>
  <%= @wine.bottle_size_in_ml %>
</p>

<p>
  <strong>Price:</strong>
  <%= @wine.price %>
</p>

<p>
  <strong>Long description:</strong>
  <%= @wine.long_description %>
</p>

<p>
  <strong>Country of origin:</strong>
  <%= @wine.country_of_origin %>
</p>

<p>
  <strong>Grade type:</strong>
  <%= @wine.grade_type %>
</p>

<p>
  <strong>Image</strong>
  <%= @wine.image %>
</p>

<p>
  <strong>Suitable for vegetarians:</strong>
  <%= @wine.suitable_for_vegetarians %>
</p>

<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>