MAF/maf/config/routes.rb
Rails.application.routes.draw do

  resources :line_items

  resources :carts

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'welcome/index'

  resources :wines do
    get 'search', on: :collection
    get 'price_filter', on: :collection
  end

  resources :customers

   root 'welcome#index'

end

MAF/maf/app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy


	# Adds wine & quantity of wines being purchased to Lineitem
	# Creates new LineItem if one doesn't exist already
	def add_wine(wine_id, quantity)
		current_item = line_items.find_by_wine_id(wine_id)
		if current_item
			if quantity != nil && quantity > 1
				current_item.quantity += quantity
			else				
				current_item.quantity += 1
			end
		else
			if quantity != nil
				current_item = line_items.build(wine_id: wine_id, quantity: quantity)
			else
				current_item = line_items.build(wine_id: wine_id)
			end
		end
		
		current_item
	end

	# Calculate total price of items in a cart
	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end

	# Calculate total quantity of items in a cart
	def total_quantity
		line_items.to_a.sum { |item| item.quantity }
	end

end

MAF/maf/app/controllers/carts_controller.rb
require 'rest_client'
require 'rubygems'

class CartsController < ApplicationController
  include CartsHelper
  before_action :set_cart, only: [:show, :edit, :update]
  helper_method :post_to_supplier, :get_wine_image_url 

  respond_to :html

  def index
    respond_to do |format|
      format.html { redirect_to wines_url}
      format.json { render json: @customers }
    end 

    @carts = Cart.all
  end

  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to wines_url(page: @current_page), notice: 'Invalid cart'
    rescue Exception
      redirect_to wines_url(page: @current_page), notice: 'Invalid cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @cart }
      end
    end
  end 

  def create
    # First check if customer is logged in before processing checkout
    # If not logged in, redirect them to login page
    if !session[:customer_id].nil?
      @cart = current_cart
      @supplier_one_order_url, @supplier_two_order_url = get_order_url

      # Process orders and send to the appropriate suppliers
      if post_to_supplier(@cart, SUPPLIER_ONE_NAME) == true
        @cart.line_items.each do |item|
          if item.wine.supplier == SUPPLIER_ONE_NAME     
            RestClient.post "#{@supplier_one_order_url}", build_order_detail_json(item), :content_type => :json, :accept => :json
          end
        end
      end

      if post_to_supplier(@cart, SUPPLIER_TWO_NAME) == true
        @cart.line_items.each do |item|
          if item.wine.supplier == SUPPLIER_TWO_NAME
            RestClient.post "#{@supplier_two_order_url}", build_order_detail_json(item), :content_type => :json, :accept => :json
          end
        end
      end    

      #clean up cart after checkout
      @cart.destroy
      session[:cart_id] = nil
      
      respond_to do |format|
        format.html { redirect_to wines_url(page: @current_page),
        notice: 'Your Order is successful and your shopping cart is empty' }
        format.json { head :no_content }
      end
    else
      session[:to_checkout] = true
      respond_to do |format|
        format.html { redirect_to root_path,
        notice: 'Please login to checkout successfully' }
        format.json { head :no_content }
      end
    end
  end

  def get_order_url
    @suppler_one_order_url = DEV_SUPPLIER_ONE_ORDER_URL
    @suppler_two_order_url = DEV_SUPPLIER_TWO_ORDER_URL
    
    if Rails.env.production?
      @suppler_one_order_url = PROD_SUPPLIER_ONE_ORDER_URL
      @suppler_two_order_url = PROD_SUPPLIER_TWO_ORDER_URL
    end   

    return @suppler_one_order_url, @suppler_two_order_url
  end


  def new
    @cart = Cart.new
    respond_with(@cart)
  end

  def edit
  end


  def update
    @cart.update(cart_params)
    respond_with(@cart)
  end

  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil
    
    respond_to do |format|
      format.html { redirect_to wines_url(page: @current_page),
      notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end

  private
    # Set carts, but also importantly checks that invalid cart IDs typed into URL
    # are redirected to wines home page with the right notice
    def set_cart
      begin
        @cart = Cart.find(params[:id])
        if @cart.line_items.length == 0       
          redirect_to wines_url(page: @current_page), notice: 'Shopping Cart is empty'
        end
      rescue ActiveRecord::RecordNotFound
        redirect_to wines_url(page: @current_page), notice: 'Invalid cart'
      else
        #respond_to do |format|
         # format.html # show.html.erb
         # format.json { render json: @cart }
        #end
      end
    end

    def cart_params
      params[:cart]
    end
end

MAF/maf/app/helpers/carts_helper.rb
module CartsHelper
	include ApplicationHelper


	# Gets order details and rebuild attributes into json format
	# ready to be sent to web service
	def build_order_detail_json(item)
		@customer = Customer.find(session[:customer_id])

		json_order = {
		  :customer_name => "#{@customer.first_name} #{@customer.surname}",
		  :customer_address => @customer.address,
		  :customer_email => @customer.email,
		  :wine_id => item.wine.wine_unique_number,
		  :quantity => item.quantity
		}.to_json
	end 

	
	# Checks if an item in the cart belongs to a certain supplier
	def post_to_supplier(cart, supplier)
		@make_post = false
		cart.line_items.each do |item|
		  if item.wine.supplier.include? supplier
		    @make_post = true
		  end 
		end
		@make_post 
	end


end

MAF/maf/app/views/carts/_carts_list.erb
<div class="row">
    <div class="col-sm-12 col-md-10 col-md-offset-1">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Wine</th>
                    <th>Quantity</th>
                    <th class="text-center">Price</th>
                    <th class="text-center">Total</th>
                    <th> </th>
                </tr>
            </thead>
            <tbody>
            	<% @cart.line_items.each do |item| %>
                <tr>
                    <td class="col-sm-8 col-md-6">
                    <div class="media">
                        <%= link_to(image_tag(get_wine_image_url(item.wine), alt: 'Wine', title: 'Show details', :class => 'media-object', :style => 'width: 72px; height: 72px;'), wine_path(item.wine, page: 1), :class => 'thumbnail pull-left') %>

                        <div class="media-body" style="padding-left: 5px;">
                            <h4 class="media-heading"><a href="#"><%= item.wine.name %></a></h4>
                            <h5 class="media-heading"> by <a href="#"><%= item.wine.supplier %></a></h5>
                            <span>Status: </span><span class="text-success"><strong>In Stock</strong></span>
                        </div>
                    </div></td>
                    <td class="col-sm-1 col-md-1" style="text-align: center">
                    <p> <%= item.quantity %> </p>
                    </td>
                    <td class="col-sm-1 col-md-1 text-center"><strong>£<%= !item.wine.price.nil? ? "%.2f" % item.wine.price : 0 %> </strong></td>
                    <td class="col-sm-1 col-md-1 text-center"><strong>£<%= !item.total_price.nil? ? "%.2f" % item.total_price : 0 %></strong></td>
                    <td class="col-sm-1 col-md-1">
                    <%= button_to 'Remove Item(s)', item, method: :delete,confirm: 'Are you sure?', :class => "btn btn-danger" %></td>
                </tr>
                <% end %>
                <tr>
                    <td>   </td>
                    <td>   </td>
                    <td>   </td>
                    <td><h3>Total</h3></td>
                    <td class="text-right"><h3><strong>£<%= "%.2f" % @cart.total_price %></strong></h3></td>
                </tr>
                <tr>
                    <td><%= button_to 'Empty cart', @cart, method: :delete,confirm: 'Are you sure?', :class => "btn btn-danger" %>   
                    </td>
                    <td>   </td>
                    <td>
                    </td>
                    <td>
                    <%= link_to 'Continue Shopping', wines_path, :class => "btn btn-default", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Continue Shopping..."} %> 
                    </td>
                    <td>
                    <%= button_to 'Checkout', carts_path(cart_id: @cart), :class => "btn btn-success", data: {disable_with: "Checking out..."} %>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

MAF/maf/app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MAF/maf/app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

MAF/maf/app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

MAF/maf/app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

MAF/maf/app/views/carts/show.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>
<h2 class="page-title">Your Cart</h2>

<div class="container">
    <%= render partial: 'carts_list', object: @cart %>
</div>