MAF/maf/config/routes.rb
Rails.application.routes.draw do

  resources :line_items

  resources :carts

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'welcome/index'

  resources :wines do
    get 'search', on: :collection
    get 'price_filter', on: :collection
  end

  resources :customers

   root 'welcome#index'

end

MAF/maf/app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :wine
	belongs_to :cart

	# Calculate total price of one item in a cart
	def total_price
		if !wine.nil?
			wine.price * quantity
		else
			0
		end
	end
end

MAF/maf/app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    respond_to do |format|
      format.html { redirect_to wines_url}
      format.json { render json: @customers }
    end   
    @line_items = LineItem.all
  end

  def show
    @cart = current_cart
    respond_with(@line_item)
  end

  def new
    @cart = current_cart
    @line_item = LineItem.new
    respond_with(@line_item)
  end

  def edit
     @cart = current_cart
  end

  # Creates new lineItem in a cart
  def create
    @cart = current_cart
    wine = Wine.find(params[:wine_id])

    # Gets Quantity and convert to integer
    quantity = params[:the_quantity].to_i

    # Add new wine and quantity using the add_wine method from Cart.rb
    # Sets quantity to a default of '1' if quantity isn't specified
    @line_item = @cart.add_wine(wine.id, quantity > 0 ? quantity : 1)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart}
        format.json { render json: @line_item, status: :created, location: @line_item }
      else
        format.html { render action: "new" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @line_item.update(line_item_params)
    respond_with(@line_item)
  end

  def destroy
    @cart = current_cart
    @line_item.destroy
    respond_to do |format|
      if @cart.line_items.length > 0
        format.html { redirect_to @line_item.cart}
        format.json { render json: @line_item, status: :created, location: @line_item }      
      else
        format.html { redirect_to wines_url(page: @current_page),
        notice: 'Your cart is currently empty' }
        format.json { head :no_content }
      end
    end
    #respond_with(@line_item)
  end

  private
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    def line_item_params
      params.require(:line_item).permit(:wine_id, :cart_id, :the_quantity)
    end
end

MAF/maf/app/helpers/line_items_helper.rb
module LineItemsHelper
end

MAF/maf/app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :wine_id %><br>
    <%= f.number_field :wine_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.number_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MAF/maf/app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

MAF/maf/app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Wine</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.wine_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

MAF/maf/app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

MAF/maf/app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wine:</strong>
  <%= @line_item.wine_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>